window.OPTIQ_REQUESTS = [
  {
    "id": "conformity",
    "area": "Reports & analyses",
    "status": "optiq",
    "title": "Conformity testing",
    "description": "Compare several vials for Net Content, Purity, or Identity, with repeat results and a summary on the COA.",
    "detail": "The repeat-vial workflow and detailed COA layout have been built in parts. Full Net Content, Purity and Identity names, an extra detail page, and both agreed routes—fresh independent vials or a suitable original result as the first repeat—must be preserved. Final acceptance limits, customer ordering setup and repeat-vial pricing still need confirmation. Conformity is not available and was explicitly excluded from the 4 October receiving release.",
    "question": "Confirm the final acceptance limits for each test and the customer ordering and repeat-vial pricing setup. The agreed test names and repeat routes do not need to be chosen again.",
    "evidence": "Work started; lab pricing and pass/fail rules still needed.",
    "stage": 1,
    "nextStep": "Finish the remaining lab criteria, ordering and pricing setup; preserve the agreed names and repeat routes.",
    "discussedDate": "2026-10-02",
    "meetingDate": "2026-09-30",
    "meetingPriority": true
  },
  {
    "id": "inspection-rules",
    "area": "Receiving",
    "status": "optiq",
    "title": "Visual inspection and COA rules",
    "description": "Agree what the visual check records and which findings should appear on the COA.",
    "detail": "The lab will review examples from other testing labs. Seal integrity, cap color, and an intact vial are the starting checks. Recording powder appearance or visible amount, and handling damaged or empty vials on the COA or through customer follow-up, still need the lab’s decision.",
    "question": "Share inspection examples and confirm what to record, including powder appearance or visible amount, and which problems belong on the COA or need a customer reply first.",
    "evidence": "Starting checks agreed; final inspection and COA rules still needed.",
    "stage": 0,
    "nextStep": "The lab shares other labs’ inspection examples and finalizes what to record and what belongs on the COA; implement the three agreed starting checks separately.",
    "discussedDate": "2026-10-02",
    "meetingPriority": true,
    "meetingDate": "2026-10-02"
  },
  {
    "id": "batch-templates",
    "ref": "R31",
    "area": "Inventory & operations",
    "status": "optiq",
    "title": "Batch and preparation sheets",
    "description": "Use repeatable daily preparation sheets and put vials in the correct instrument order.",
    "detail": "Some of the tools are already available. We need the lab’s worksheet and vial order to tailor them to Optiq.",
    "question": "Share your current preparation sheet and the order vials should run in.",
    "evidence": "Starting tools available; lab details needed.",
    "stage": 0,
    "nextStep": "Share your current preparation sheet and the order vials should run in.",
    "meetingPriority": true,
    "meetingDate": "2026-09-30"
  },
  {
    "id": "verify-results",
    "status": "complete",
    "stage": 3,
    "title": "Verify Results — real certificate lookup",
    "description": "Look up a certificate on the Optiq website and compare it with the lab’s released record.",
    "detail": "The website was connected to real released COAs and tested with an older printed certificate number, the sample photo, and a phone-sized screen. The recorded release was September 27. The September 30 font adjustment is listed separately. The meeting agreed to keep the COA’s QR code opening its digital version.",
    "evidence": "Released and checked on the Optiq website · 27 Sep 2026.",
    "nextStep": "Available on the website; keep the QR code opening the digital COA.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "verify-results-font",
    "status": "queued",
    "stage": 0,
    "title": "Verification Record — compare font options",
    "description": "Show different fonts on the document-style record returned by Verify Results, using the same content and layout for a fair comparison.",
    "detail": "The September 30 meeting requested a font change and an example before publication. On October 4 Mike clarified that the next action is to mock up different fonts on the returned Verification Record. The working certificate lookup is already released; these record-font examples and the chosen typography are a separate unfinished action.",
    "evidence": "Example requested · 30 Sep; multiple-font comparison clarified · 4 Oct 2026.",
    "nextStep": "Work next: mock up font options on the same Verification Record, review the examples, then publish the chosen typography.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30",
    "nextReview": true,
    "meetingPriority": true
  },
  {
    "id": "coa-mass-spectra",
    "status": "built",
    "stage": 2,
    "title": "Mass spectra on COAs",
    "description": "Choose one or more measured spectra and show them with the sample’s chromatogram, including blends.",
    "detail": "The spectrum picker, saved selections, and separate labeled COA pages are built and tested. The default for choosing peaks was changed to PDA in the recorded 1 October release and is listed separately. Complete instrument imports and final COA generation at Optiq still need matching proof. Multiple spectra can be selected for a blend; that alone does not establish complete delivery.",
    "evidence": "Spectrum selection and multi-spectrum COA pages built and tested.",
    "nextStep": "Confirm the full import → selected spectra → generated COA journey at Optiq.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30",
    "meetingPriority": true
  },
  {
    "id": "spectral-reference-library",
    "status": "built",
    "stage": 2,
    "title": "Reference standards for spectrum comparisons",
    "description": "Keep the lab’s reference spectra in a library and compare samples against them.",
    "detail": "The September 30 meeting requested a standards selector and a reusable library. A lab-owned library with draft standards, source records, and saved comparisons has since been built and tested. It is not released at Optiq. These comparisons do not automatically confirm Identity or change a released COA; the lab must establish the standards and method used.",
    "evidence": "Library and comparison screens built and tested; not released.",
    "nextStep": "Finish the current build checks and merge steps, then release and validate the library with the lab’s chosen standards.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30",
    "meetingPriority": true
  },
  {
    "id": "fentanyl-results",
    "status": "queued",
    "stage": 0,
    "title": "Fentanyl test results",
    "description": "Record the fentanyl test outcome and show it clearly on the COA.",
    "detail": "The September 30 meeting requested a simple outcome such as detected or not detected, with an agreed pass/fail presentation. That display request is recorded. A matching completed feature or release record was not found. Final wording must follow the lab’s actual test and reporting rules.",
    "evidence": "Requested · 30 Sep 2026; implementation planned.",
    "nextStep": "Add the result entry and COA display, then check them against the lab’s reporting rules.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30",
    "meetingPriority": true
  },
  {
    "id": "requested-white-label-photo",
    "status": "queued",
    "stage": 0,
    "title": "Choose the photo on a customer’s white-label request",
    "description": "Let authorized lab staff change the selected photo while reviewing a customer-requested white-label COA.",
    "detail": "On September 30 the lab reported that the photo could not be changed when the customer had requested the COA. The existing private-draft editor does not cover requests still awaiting customer-request approval. This specific case needs a fix and a screen test. Changes must keep the previously released certificate intact.",
    "evidence": "Specific photo-selection problem recorded · 30 Sep 2026.",
    "nextStep": "Fix photo selection during lab review and test it before approval.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30",
    "meetingPriority": true
  },
  {
    "id": "coa-summary-layout",
    "status": "queued",
    "stage": 0,
    "title": "COA summary with extra test pages",
    "description": "Show a readable first-page snapshot, followed by separate detailed test pages.",
    "detail": "The September 30 meeting agreed on a useful first-page snapshot, then detailed Conformity, visual inspection, chromatogram and mass-spectrum pages. A blend may need several separately labeled spectra. The concrete next action is to show representative layout examples, retaining full test names and the distinction between Tested, Pass and failed outcomes. Existing multi-page tools do not establish that the combined new layout or unfinished tests are available.",
    "evidence": "Page structure agreed · 30 Sep 2026; existing layouts available.",
    "nextStep": "Show first-page and extra-page examples, review readability, then qualify the supported results through final COA generation.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30",
    "meetingPriority": true
  },
  {
    "id": "receipt-emails",
    "area": "Receiving",
    "status": "complete",
    "title": "Sample-received emails",
    "description": "Tell customers when all or some of their samples have arrived.",
    "detail": "Receipt emails are included in the current Optiq release and have been tested with a test inbox. Delivery to the correct customer inboxes still needs confirmation from delivery records. The approved photo-and-answer flow is a separate item; a complete two-stage drop-off and verification message sequence is not established by these email tests.",
    "evidence": "Included in the current Optiq release · checked 3 Oct 2026. Customer inbox delivery remains to be confirmed.",
    "stage": 3,
    "nextStep": "Confirm the intended recipients and inbox delivery from receipt-email records.",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "customer-photos",
    "area": "Receiving",
    "status": "built",
    "title": "Customer photo requests and replies",
    "description": "Send a customer a photo when the lab cannot identify a sample, then review their answer.",
    "detail": "The photo-and-answer software was deployed at Optiq on 4 October 2026, but the feature is still switched off. It passed browser tests with test accounts: staff select the order and received-item photo, the customer chooses a matching sample or “None of these samples,” and staff independently review the answer. Turning it on remains separately held; deploying the software does not enable customer requests or notifications.",
    "evidence": "Software deployed · 4 Oct 2026; feature remains off.",
    "stage": 2,
    "nextStep": "Keep off until separate approval and the required customer-access, private-photo, and notification checks are complete.",
    "discussedDate": "2026-10-02",
    "meetingPriority": true,
    "meetingDate": "2026-10-02"
  },
  {
    "id": "inspection-checks",
    "area": "Receiving",
    "status": "queued",
    "title": "Seal integrity, cap color, and intact vials",
    "description": "Record three checks when samples arrive: whether the seal is intact, the cap color, and whether the vial is intact or broken.",
    "detail": "Today’s call agreed these three checks as the starting point. Some receiving checks exist already, but seal observations still need to save correctly. All three checks then need testing.",
    "evidence": "Three starting checks agreed · 2 Oct 2026; remaining work planned.",
    "stage": 0,
    "nextStep": "Add the three agreed checks, make sure they save, and test them.",
    "discussedDate": "2026-10-02",
    "meetingPriority": true,
    "meetingDate": "2026-10-02"
  },
  {
    "id": "invoice-status",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Invoice status",
    "description": "See and update invoice status in Reporting Hub.",
    "detail": "The Invoiced, Paid, and Unpaid dropdown, saving, paste/fill, and undo/redo were released to Optiq and have recorded screen-test proof. The current release still includes them. This is invoice record-keeping; it does not take payments.",
    "evidence": "Included in the current Optiq release · checked 3 Oct 2026. Invoice record-keeping, with recorded screen tests.",
    "stage": 3,
    "nextStep": "No new release needed. Report an example if the dropdown or saving does not work as expected."
  },
  {
    "id": "frozen-sort",
    "area": "Reports & analyses",
    "status": "queued",
    "title": "Keep rows still while editing",
    "description": "Keep a row in place while you edit it, then sort again when you are ready.",
    "detail": "Reporting Hub already sorts rows. The option to hold that order while editing still needs to be added and tested.",
    "evidence": "Planned.",
    "stage": 0,
    "nextStep": "Add the option to keep rows still and sort again when finished."
  },
  {
    "id": "receiving-tables",
    "area": "Receiving",
    "status": "complete",
    "title": "Updated receiving order and sample tables",
    "description": "Use the updated order and sample tables for submission and accessioning.",
    "detail": "Released at Optiq on 4 October 2026. The submission and accessioning screens now use the updated receiving tables. Editing, permissions, selection, grouping, search, paste and undo, and screen layouts were checked in the running system before release. Existing saved layouts are preserved. This does not complete the separate intake-station scanning or drop-off and verified-intake workflow.",
    "evidence": "Released at Optiq · 4 Oct 2026; receiving tables browser-tested before release.",
    "stage": 3,
    "nextStep": "Available now. Check the updated tables during normal submission and accessioning.",
    "completed": "Recorded release"
  },
  {
    "id": "lot-number",
    "area": "Receiving",
    "status": "complete",
    "title": "Lot / Batch number",
    "description": "Show the Lot / Batch number automatically in the sample receiving table.",
    "detail": "Released at Optiq on 4 October 2026. Lot / Batch is shown in the default sample receiving layout. Existing saved layouts stay intact; use “Reset to Lab Default” if an older saved layout hides the column.",
    "evidence": "Released at Optiq · 4 Oct 2026.",
    "stage": 3,
    "nextStep": "Available now. Use “Reset to Lab Default” if a saved layout hides Lot / Batch.",
    "completed": "Recorded release"
  },
  {
    "id": "printed-labels",
    "area": "Labels",
    "status": "queued",
    "title": "Printed label choices",
    "description": "Choose separately whether labels show test symbols, three-letter test names, or both.",
    "detail": "Labels can already be printed. These separate choices still need to be added, then checked on actual printed labels.",
    "evidence": "Planned.",
    "stage": 0,
    "nextStep": "Add the choices and check the printed labels."
  },
  {
    "id": "client-scrolling",
    "area": "Client management",
    "status": "complete",
    "title": "Manage Clients scrolling",
    "description": "Scroll through the client list without the reported problem.",
    "detail": "Earlier feedback confirmed the problem was fixed. If it happens again, we will need an example to investigate.",
    "evidence": "Reported fixed.",
    "stage": 3,
    "completed": "Reported resolved",
    "nextStep": "No further work recorded."
  },
  {
    "id": "net-content-editing",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Net Content copy, paste, and fill",
    "description": "Enter Net Content amounts and units, or copy them across several rows.",
    "detail": "Value-only and value-with-unit copy, paste, and fill are included in the current Optiq release, with recorded save-and-reload screen tests. Adding IU and choosing the lab’s allowed units are separate items. Reliable undo of a drag-fill remains a separate follow-up.",
    "evidence": "Included in the current Optiq release · checked 3 Oct 2026. Drag-fill undo is tracked separately.",
    "stage": 3,
    "nextStep": "Use the existing copy, paste, and fill tools; the separate drag-fill undo follow-up remains open."
  },
  {
    "id": "universal-import",
    "area": "Reports & analyses",
    "status": "partial",
    "title": "Import results by Sample ID",
    "description": "Upload result files and match each result to the correct Sample ID.",
    "detail": "Importing exists for chemistry panels and Net Content. The August 20 deliverable also included sample/analyte matching, units, applicable action limits and LOD/LOQ, an import preview, row-level errors and avoiding accidental assignment to similarly named repeat samples. Coverage for every requested peptide test and those detailed acceptance checks still needs confirmation.",
    "evidence": "Partly built; the remaining peptide tests still need to be checked.",
    "stage": 2,
    "nextStep": "Check each requested peptide test and its sample matching, units, preview and row-level error handling.",
    "meetingDate": "2026-08-20",
    "meetingPriority": true
  },
  {
    "id": "grid-widths",
    "area": "Reports & analyses",
    "status": "partial",
    "title": "Readable columns and width choices",
    "description": "Let columns widen to fit their contents, or keep a width you choose.",
    "detail": "Readable Reporting Hub columns were released to Optiq on 3 October 2026. Columns grow when newly shown values need more room, while saved and manual widths remain respected. The separate Auto / Fixed choices in Settings are built but were not included in that release; their remaining screen checks and release preparation are still open.",
    "evidence": "Readable columns released 3 Oct 2026. Auto / Fixed settings remain built, not released.",
    "stage": 2,
    "nextStep": "Finish the Auto / Fixed settings checks and release preparation. The readability improvement is already available."
  },
  {
    "id": "inventory-release",
    "area": "Inventory & operations",
    "status": "complete",
    "title": "Inventory and reference-standard values",
    "description": "Manage inventory, test substances, certified lot values, and receiving in the updated Inventory screens.",
    "detail": "Our release records show the agreed Inventory update was made available on 28 September 2026.",
    "evidence": "Released · 28 Sep 2026.",
    "stage": 3,
    "completed": "Recorded release",
    "nextStep": "Released · 28 Sep 2026."
  },
  {
    "id": "iu-units",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "IU and Net Content units",
    "description": "Report Net Content in IU or other units selected by the lab.",
    "detail": "Our release records show this was made available on 1 October 2026. Existing saved amounts and units were kept without converting the numbers.",
    "evidence": "Released · 1 Oct 2026.",
    "stage": 3,
    "completed": "Recorded release",
    "nextStep": "Released · 1 Oct 2026."
  },
  {
    "id": "preview-performance",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Faster photo and chart previews",
    "description": "Load smaller previews of photos, chromatograms, and spectra in Reporting Hub.",
    "detail": "The improvement was released on 1 October 2026. Scrolling was tested before release; its speed during everyday use at Optiq has not been measured separately.",
    "evidence": "Released · 1 Oct 2026.",
    "stage": 3,
    "completed": "Recorded release",
    "nextStep": "Released · 1 Oct 2026."
  },
  {
    "id": "sop-documents",
    "area": "Inventory & operations",
    "status": "built",
    "title": "Documents, Forms, Logs, and NCRs",
    "description": "Edit documents, keep earlier versions, correct forms and logs, and track quality issues such as nonconformance reports (NCRs).",
    "detail": "These features have been built and tested on screen. Making them available at Optiq is still pending. Document signing and shared templates are listed separately. The August 27 meeting separately called for one accessible controlled master SOP, assisted import of existing drafts, reusable templates and a chronological record of what changed, when, by whom, why and under which change request. Those complete outcomes require their own qualification; an editor alone does not establish them.",
    "evidence": "Built and tested; waiting to be made available.",
    "stage": 2,
    "nextStep": "Finish the release checks and make these features available at Optiq.",
    "meetingDate": "2026-08-27",
    "meetingPriority": true
  },
  {
    "id": "partner-inventory",
    "area": "Inventory & operations",
    "status": "working",
    "title": "Sharing stock information with partner labs",
    "description": "Choose which stock information a partner lab can see while keeping each lab’s inventory separate.",
    "detail": "Work has started on choosing what to share. Requests, transfers, receiving, and handling missing or damaged items are not yet complete.",
    "evidence": "Partly built; partner-lab process still needs work.",
    "stage": 1,
    "nextStep": "Finish how partner labs request, transfer, and receive stock.",
    "meetingPriority": true,
    "meetingDate": "2026-09-16"
  },
  {
    "id": "manufacturer-profiles",
    "area": "Reports & analyses",
    "status": "queued",
    "title": "Saved manufacturers and early white-label requests",
    "description": "Choose a saved manufacturer and request a white-label COA when submitting samples.",
    "detail": "Manufacturer names can already be entered by hand. The August 20 meetings also called for keeping client/brand and manufacturer separate, saving reusable manufacturer choices, and carrying Manufactured By through submission, stored sample details, lab tables, imports/exports and the released COA. Saved choices and early white-label requests still need work; the complete end-to-end field journey needs its own evidence check.",
    "evidence": "Planned; manual name entry already available.",
    "stage": 0,
    "nextStep": "Finish saved manufacturer choices and early white-label requests; check the complete Manufactured By field journey.",
    "meetingDate": "2026-08-20",
    "meetingPriority": true
  },
  {
    "id": "client-bulk-white-label",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Client requests for several white-label COAs",
    "description": "Let clients request white-label COAs for several samples at once.",
    "detail": "The client bulk-request screen and the steps for saving and submitting several white-label COAs are built. Screen tests and software checks are recorded. We have not confirmed current availability for Optiq’s client accounts.",
    "evidence": "Built and tested; client availability at Optiq still needs confirmation.",
    "stage": 2,
    "nextStep": "Confirm that Optiq clients can open and use the bulk-request screen.",
    "meetingPriority": true,
    "meetingDate": "2026-08-20"
  },
  {
    "id": "white-label-drafts",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Private white-label drafts",
    "description": "Edit a draft COA and the client name printed on it before it is released.",
    "detail": "The changes are built and have passed software checks. The screens still need to be tested, and availability at Optiq has not been confirmed. This covers eligible private drafts; changing the photo on a customer request still awaiting approval is a separate item below.",
    "evidence": "Built; screen checks and release still needed.",
    "stage": 2,
    "nextStep": "Complete the real screen test, finish the review and merge steps, and confirm release to Optiq.",
    "meetingPriority": true,
    "meetingDate": "2026-09-30"
  },
  {
    "id": "blend-potency",
    "area": "Reports & analyses",
    "status": "queued",
    "title": "Results for each peptide in a blend",
    "description": "Enter a separate result for each peptide in a blend and show those results on the COA.",
    "detail": "The COA layout is ready, while separate result entry and report integration still need work. The August 20 meeting also requested a structured multi-component display rather than slash-separated values, with each identity and Net Content value kept with its component. Check four-component mixtures, long names, page breaks and stable signature placement in both PDF and digital reports.",
    "evidence": "COA layout ready; result entry planned.",
    "stage": 1,
    "nextStep": "Finish per-peptide result entry and prove four-component PDF and digital reports remain readable.",
    "meetingDate": "2026-08-20",
    "meetingPriority": true
  },
  {
    "id": "photo-reliability",
    "area": "Receiving",
    "status": "complete",
    "title": "Clear intake photos and hide / restore orders",
    "description": "View clear original photos and hide or restore an order in Intake without deleting its samples or results.",
    "detail": "These features were released to Optiq on 9 September 2026. Full-size photos and hiding, reloading, and restoring an order were tested before release. The separately reported missing order is listed as its own item.",
    "evidence": "Released · 9 Sep 2026.",
    "stage": 3,
    "nextStep": "Released · 9 Sep 2026.",
    "completed": "Recorded release"
  },
  {
    "id": "scan-intake",
    "area": "Receiving",
    "status": "working",
    "title": "Scan, review, and receive samples",
    "description": "Scan an order, review and correct its sample list, then confirm what arrived.",
    "detail": "At a fixed intake station, scanning must open the matching order for manual staff review; it must not automatically receive samples. Staff need to add, remove, rename or confirm physical samples before receipt. The August 27 meeting separately requested provisional drop-off confirmation and a later verified-intake outcome. Existing scanning and a received email do not prove that complete two-stage process. A dedicated intake workstation remains a setup dependency.",
    "evidence": "Partly built; complete receiving process still needs work.",
    "stage": 1,
    "nextStep": "Finish and prove fixed-station scan → manual review → receipt, with separate drop-off and verified-intake outcomes.",
    "meetingDate": "2026-08-27",
    "meetingPriority": true
  },
  {
    "id": "certified-imports",
    "area": "Inventory & operations",
    "status": "queued",
    "title": "Export and import certified lot values",
    "description": "Export lot values as a CSV spreadsheet file and read values from a reference-standard COA.",
    "detail": "Values can already be entered by hand. Spreadsheet export and reading values from a document are still planned.",
    "evidence": "Manual entry available; import and export planned.",
    "stage": 0,
    "nextStep": "Add spreadsheet export and importing values from a COA."
  },
  {
    "id": "purchasing",
    "area": "Inventory & operations",
    "status": "working",
    "title": "Purchasing follow-ups",
    "description": "Handle vendor replies, suggest values from invoices, manage item requests, and flag orders needing attention.",
    "detail": "Order history, imports, and tracking are built and listed separately. These additional purchasing features still need to be finished and made available.",
    "evidence": "Further purchasing features in progress.",
    "stage": 1,
    "nextStep": "Finish vendor replies, invoice suggestions, and the expanded attention list."
  },
  {
    "id": "instrument-workflow",
    "ref": "R02",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Empower run lists and source files",
    "description": "Prepare instrument run lists and keep track of the original data and where it came from.",
    "detail": "Run-list and source-file provenance tools have been built. Their use on the lab’s instrument computer is not yet confirmed. Automatic native Empower collection and the released native-chart display repair are separate items in this list.",
    "evidence": "Built; instrument setup and use not yet confirmed.",
    "stage": 2,
    "nextStep": "Confirm the run-list and source-file workflow works with the lab’s instrument computer."
  },
  {
    "id": "retained-intent",
    "ref": "R03",
    "area": "Receiving",
    "status": "queued",
    "title": "Recover archived portal request details",
    "description": "Keep the original details of older portal requests so they can be found and recovered.",
    "detail": "This request is on the planned list. A matching finished feature has not been verified. The next step is to match the original request to the existing archive tools, then finish and test any missing recovery steps.",
    "evidence": "Planned; no matching completed feature verified.",
    "stage": 0,
    "nextStep": "Match the original request to the archive tools, then finish and test the missing steps."
  },
  {
    "id": "intake-identity",
    "ref": "R33",
    "area": "Receiving",
    "status": "complete",
    "title": "Peptide names and mixtures during intake",
    "description": "Clearly show which peptide or mixture is being submitted in the intake table.",
    "detail": "Peptide names and mixtures can be selected directly in the sample table. Saved choices are retained when the page is reloaded, and the Peptide Identity column follows Sample Type. These changes were released to Optiq on 10 September 2026.",
    "evidence": "Released · 10 Sep 2026.",
    "stage": 3,
    "nextStep": "Released · 10 Sep 2026.",
    "completed": "Recorded release"
  },
  {
    "id": "analysis-framework",
    "area": "Reports & analyses",
    "status": "working",
    "title": "Lab-specific testing steps",
    "description": "Set up the lab’s preparation, result entry, and review steps for each test.",
    "detail": "The first method-setup tools are built and listed separately. The full process still needs to carry the correct results from entry through review to the COA.",
    "evidence": "Setup tools partly ready; complete testing process still needs work.",
    "stage": 1,
    "nextStep": "Finish and test the steps from preparation and result entry through to the COA.",
    "meetingPriority": true,
    "meetingDate": "2026-09-30"
  },
  {
    "id": "document-release",
    "area": "Inventory & operations",
    "status": "queued",
    "title": "Document signing and shared templates",
    "description": "Approve and sign the current document version, and reuse templates across labs.",
    "detail": "Document editing and saved versions are built. The complete signing and release process, and sharing templates across labs, still need work. Preserve the meeting request for reusable templates across labs, controlled approval/effectivity, and readable change history from one master document.",
    "evidence": "Planned follow-up to the document editor.",
    "stage": 0,
    "nextStep": "Finish document approval, signing, and shared templates.",
    "meetingDate": "2026-08-27",
    "meetingPriority": true
  },
  {
    "id": "purchasing-core",
    "area": "Inventory & operations",
    "status": "complete",
    "title": "Purchasing history, imports, and tracking",
    "description": "Track each purchase order, import earlier orders, and see which orders need attention.",
    "detail": "Purchase-order tracking, earlier-order imports, and the needs-attention list are included in the current Optiq release and have recorded checks. The lab’s access, setup, and everyday use still need confirmation; this item no longer awaits a new software release.",
    "evidence": "Included in the current Optiq release · checked 3 Oct 2026. Lab access and setup checks remain.",
    "stage": 3,
    "nextStep": "Confirm the lab can open the purchasing tools and that the required setup is in place."
  },
  {
    "id": "reporting-method-drafts",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Draft method setup",
    "description": "Use existing report fields to prepare a draft method in Analysis Settings.",
    "detail": "Creating and saving inactive method drafts was built and tested, then included in the recorded Optiq release on 1 October 2026. A saved draft does not activate a test method or complete its result-entry and COA workflow. The signed-in live draft screen has not been separately verified.",
    "evidence": "Recorded release · 1 Oct 2026; signed-in live use not confirmed.",
    "stage": 3,
    "nextStep": "Confirm signed-in use at Optiq; full testing workflows remain a separate item.",
    "completed": "Recorded release"
  },
  {
    "id": "staff-scan-access",
    "area": "Receiving",
    "status": "complete",
    "title": "Staff search, scanning, and protected edits",
    "description": "Let signed-in staff search and scan labels while protecting sample saves, editing locks, and stored-photo changes.",
    "detail": "Released at Optiq on 4 October 2026. Existing staff search and label extraction remain available. Sample saves, editing locks, and changes to stored photos now enforce the existing permissions. This does not complete the separate intake-station scanning and two-stage receiving request.",
    "evidence": "Staff editing protections released at Optiq · 4 Oct 2026; browser-tested before release.",
    "stage": 3,
    "nextStep": "Available now. Saves, locks, and stored-photo changes require the existing editing permissions.",
    "completed": "Recorded release"
  },
  {
    "id": "multi-lab-login",
    "area": "Lab access",
    "status": "queued",
    "title": "One login and easy lab switching",
    "description": "Use one personal login and switch between the labs you are allowed to access.",
    "detail": "Today’s call preferred an easy lab selector, like switching companies in QuickBooks. Each lab keeps its own dashboard, reports, and permissions. A design is ready, but this has not been built or released.",
    "evidence": "Design ready; building is planned.",
    "nextStep": "Build and test personal logins with a lab selector and separate permissions for each lab.",
    "stage": 0,
    "addedDate": "2026-10-02",
    "discussedDate": "2026-10-02",
    "meetingPriority": true,
    "meetingDate": "2026-10-02"
  },
  {
    "id": "shared-feature-tracker",
    "area": "Planning & communication",
    "status": "complete",
    "title": "Shared feature list and questions",
    "description": "Share one list of requests, progress, and questions for the lab.",
    "detail": "This public list is published and checked. Anyone with the link can search requests, open details and copy the lab questions. The October 2 call also asked for owners, blockers, next steps and rollout priorities. A separate signed-in LIMS tracker has been built for saved shared priorities; it is not established as available at Optiq. Publishing this page does not deliver that separate collaborative workflow.",
    "evidence": "Published and checked · 2 Oct 2026.",
    "nextStep": "Use this list for discussion; check the separate signed-in shared-priority workflow and keep owners, blockers and next steps current.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "missing-order-recovery",
    "area": "Receiving",
    "status": "complete",
    "title": "Reported missing order",
    "description": "Resolve the report about a photo-heavy order that appeared to be missing.",
    "detail": "The report about the missing order has been cleared up. No further action is needed for this item.",
    "evidence": "Reported resolved · 2 Oct 2026.",
    "nextStep": "Resolved · 2 Oct 2026.",
    "stage": 3,
    "completed": "Reported resolved",
    "resolvedDate": "2026-10-02"
  },
  {
    "id": "net-content-undo",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Undo a Net Content drag-fill",
    "description": "Undo a fill across several samples and keep the restored values after saving.",
    "detail": "The follow-up fix is written and has passed software tests. Its real screen test and independent review are still pending. It has not been released; the existing copy, paste, and fill feature is listed separately.",
    "evidence": "Fix built; screen test and review pending.",
    "nextStep": "Test undo and reload on the real screen, complete review, and confirm release.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "bulk-coa-amendments",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Correct several COAs together",
    "description": "Prepare corrected COAs for several selected samples while preserving the earlier released certificates.",
    "detail": "The bulk amendment fix is built and has recorded software checks. It checks which samples can be amended and preserves the prior released COA until a replacement is released. Current availability at Optiq and a complete amendment journey have not been confirmed here. This is separate from bulk white-label requests.",
    "evidence": "Built; current Optiq availability and full journey not confirmed.",
    "nextStep": "Confirm the complete select → generate → review → replacement-release journey at Optiq.",
    "stage": 2,
    "addedDate": "2026-10-02",
    "meetingPriority": true,
    "meetingDate": "2026-09-30"
  },
  {
    "id": "pda-peak-default",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Use PDA first when choosing spectrum peaks",
    "description": "Start peak selection from the PDA chromatogram while using the mass-spectrum data for the spectrum.",
    "detail": "The PDA default was built and tested, then included in the recorded Optiq release on 1 October 2026. Staff can still explicitly choose the other supported peak source, and the existing fallback remains when PDA is unavailable. The signed-in live picker has not been separately verified.",
    "evidence": "Recorded release · 1 Oct 2026; signed-in live picker not confirmed.",
    "nextStep": "Confirm the PDA default in the signed-in Optiq picker.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "completed": "Recorded release"
  },
  {
    "id": "native-empower-charts",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Display charts from native Empower source data",
    "description": "Show charts when retained native Empower evidence is available.",
    "detail": "The chart display repair was included in the recorded Optiq release on 1 October 2026. Stored-trace rendering was tested locally, and release and health checks were recorded. This repairs how available evidence is displayed; it does not prove every run has been imported or that automatic collection is active.",
    "evidence": "Recorded release · 1 Oct 2026; complete collection remains separate.",
    "nextStep": "Confirm the affected sample charts during normal lab use.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "completed": "Recorded release"
  },
  {
    "id": "empower-native-collection",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Automatic Empower imports and recovery",
    "description": "Collect completed Empower runs without a manual export and recover interrupted imports.",
    "detail": "The source collector, retained data, sample matching, recovery tools, and local status screen are built with recorded tests. Installation, secure setup, and activation at Optiq remain separate release steps. A normal subsequent lab run, live interruption recovery, and import timing still need acceptance proof. No complete instrument delivery is claimed.",
    "evidence": "Built and tested; installation, activation, and live acceptance pending.",
    "nextStep": "Prepare and release the collector, then verify a normal run and interrupted-import recovery.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "inventory-follow-ups",
    "area": "Inventory & operations",
    "status": "partial",
    "title": "Remaining Inventory screens and AI tools",
    "description": "Finish the remaining Inventory redesign and assisted entry tools.",
    "detail": "The earlier Inventory bundle is released. New Vendors, Equipment, and Composites screens have since been built, while the wider redesign and AI tools remain incomplete. Purchasing, certified-value import, and reorder suggestions have their own rows so completed pieces are not hidden inside this larger request.",
    "evidence": "Some later screens built; full redesign and AI scope incomplete.",
    "nextStep": "Finish the remaining screens and AI tools, validate each piece, and confirm release.",
    "stage": 1,
    "addedDate": "2026-10-02",
    "meetingPriority": true,
    "meetingDate": "2026-08-27"
  },
  {
    "id": "purchasing-status-words",
    "area": "Inventory & operations",
    "status": "complete",
    "title": "Use the lab’s own purchasing status words",
    "description": "Show familiar status words on purchase-order lines and retain them in history.",
    "detail": "Lab-specific purchasing status words and their saved history are included in the current Optiq release, with recorded screen and database tests. They describe the existing purchasing steps; they do not replace the underlying order status. The lab’s access and saved settings still need confirmation.",
    "evidence": "Included in the current Optiq release · checked 3 Oct 2026. Lab settings and access checks remain.",
    "nextStep": "Confirm the lab’s saved status words appear in purchasing settings and order history.",
    "stage": 3,
    "addedDate": "2026-10-02"
  },
  {
    "id": "purchase-history-forecast",
    "area": "Inventory & operations",
    "status": "complete",
    "title": "Reorder suggestions from purchase history",
    "description": "See when regularly purchased items are usually due for another order.",
    "detail": "History-based reorder suggestions are included in the current Optiq release, with recorded screen and database tests. They show typical ordering patterns rather than claiming stock is low, and do not automatically place an order. Usefulness depends on sufficient purchase history.",
    "evidence": "Included in the current Optiq release · checked 3 Oct 2026. Purchase-history usefulness still needs confirmation.",
    "nextStep": "Confirm the suggestions are useful with the lab’s existing purchase history.",
    "stage": 3,
    "addedDate": "2026-10-02"
  },
  {
    "id": "water-sample-type",
    "area": "Receiving",
    "status": "complete",
    "title": "Water sample type and clear sample symbols",
    "description": "Offer Water during peptide submission, use consistent sample-type symbols, and show the minimum volume for the selected tests.",
    "detail": "Released at Optiq on 4 October 2026, including the reviewed Water setup and sample-type symbol. The intake form shows Water and its minimum-volume guidance. This is sample classification and intake guidance; it does not introduce a validated water-testing service or settle the separate non-peptide or B12 identity question.",
    "evidence": "Released at Optiq · 4 Oct 2026; Water guidance confirmed in the live intake configuration.",
    "nextStep": "Available on the submission form. Validated water testing remains outside this release.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "completed": "Recorded release"
  },
  {
    "id": "saved-order-selections",
    "area": "Receiving",
    "status": "complete",
    "title": "Restore selected tests in saved order drafts",
    "description": "Restore available test selections when reopening a saved draft and warn when a selected test is no longer offered.",
    "detail": "Released at Optiq on 4 October 2026. Reopened drafts restore the available test selections and show a warning for a previously selected test that is no longer offered. Re-saving the draft removes unavailable selections. The reopen, warning, re-save, and reload flow was checked in the running system with test accounts before release. Recognizing an already-submitted order after a retry is a separate request.",
    "evidence": "Released at Optiq · 4 Oct 2026; saved-draft flow browser-tested before release.",
    "nextStep": "Available now. Check a reopened draft’s test selections during normal use.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "completed": "Recorded release"
  },
  {
    "id": "order-submit-retry",
    "area": "Receiving",
    "status": "built",
    "title": "Recognize an order already submitted",
    "description": "After a retry or reload, show the order that was already placed.",
    "detail": "The fix is built and tested in software for the saved-order path. A real screen test with the running system is still needed. It does not cover submissions where no saved order was opened. It remains an open candidate and is not a confirmed Optiq release.",
    "evidence": "Fix built; real screen test and release pending.",
    "nextStep": "Test submission retry and reload, finish review, and confirm release.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "configured-sample-actions",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Lab-configured Sample Details and repeat-work actions",
    "description": "Show the lab’s actual tests and supported repeat-work actions on Sample Details.",
    "detail": "The candidate uses the lab’s configured tests and permissions for result views, re-run, re-prep, confirmation, and cancel. Recorded real browser tests used test samples. Final merge and release are still pending, and unsupported testing workflows remain unavailable. This is a built part of the wider lab-specific testing framework.",
    "evidence": "Built and browser-tested candidate; release pending.",
    "nextStep": "Finish the candidate’s remaining checks and confirm release and use at Optiq.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "managed-brand-accounts",
    "area": "Client portal",
    "status": "check",
    "title": "One parent account managing several brands",
    "description": "Manage several client or brand identities through one parent portal account.",
    "detail": "The August 20 meeting described one parent account with managed brands, each retaining its own orders, samples, results, invoices and COAs. Brand/client identity and manufacturer are separate. This is different from switching between independent laboratories. Current delivery of the complete managed-brand and permission workflow has not been checked here.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check current parent/brand management, selected-brand ownership and team permissions; record any remaining work.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "white-label-attestation",
    "area": "Reports & analyses",
    "status": "check",
    "title": "White-label acknowledgement and retained consent",
    "description": "Record the customer’s acknowledgement of the approved white-label terms.",
    "detail": "The August 20 deliverable called for an affirmative acknowledgement or signature with the accepted wording version, time, user, company and related request retained. Later wording changes must not replace what was accepted. Existing white-label editing does not establish this complete consent record.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the approved wording, acknowledgement flow and retained evidence before marking it delivered.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "white-label-photo-vials",
    "area": "Receiving",
    "status": "check",
    "title": "Photography vials for each white-label brand",
    "description": "Keep each required photography vial and photo linked to the intended brand and COA.",
    "detail": "The August 20 meeting recorded a one-supplied-photography-vial-per-brand requirement, with a traceable link from brand to received vial, photograph and white-label COA. This is separate from the deployed-but-off customer photo-identification feature. Its present implementation and availability need checking.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the per-brand vial rule, required counts, received-vial/photo links and final white-label output.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "white-label-missing-vials",
    "area": "Receiving",
    "status": "check",
    "title": "Missing photography vials and white-label holds",
    "description": "Identify which expected brand vial is missing and keep the related white-label work on hold.",
    "detail": "The August 20 deliverable included an expected-vial checklist, missing or damaged observations, a customer notice identifying the affected request, and a controlled override with a reason. Clearing a hold on receipt must retain the record. The existing received email and photo reply workflow do not prove these requirements. No new customer notifications are enabled by this list update.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the checklist, hold, override, later receipt and notification journey with test records before any activation.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "white-label-required-lot",
    "area": "Receiving",
    "status": "check",
    "title": "Require Lot / Batch for white-label submissions",
    "description": "Require and retain Lot / Batch when the customer requests a white-label COA.",
    "detail": "The August 20 meeting required Lot / Batch for white-label requests. Showing the Lot / Batch column in the released receiving tables does not prove submission validation or the value’s path into the released white-label COA. A blanket requirement for ordinary submissions was not settled by that decision.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check white-label submission validation and the saved sample/COA value; preserve controlled corrections.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "client-create-invite",
    "area": "Client portal",
    "status": "check",
    "title": "Create a client and send the first portal invitation",
    "description": "Reuse entered contact details and make invitation status and resend easy to find.",
    "detail": "The August 20 deliverable called for one guided client-create/invite flow, a deliberate option to create a company without inviting anyone, clear role selection, invitation status, resend and correctly branded links. The Manage Clients scrolling fix does not establish this workflow.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check creation, invitation, roles, skipped invitation, resend and acceptance; record any remaining steps.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "public-signup-approval",
    "area": "Client portal",
    "status": "check",
    "title": "Keep public signup approval separate from invitations",
    "description": "Approve public signup requests while allowing invited users to join the correct company.",
    "detail": "The August 20 meeting retained public-signup approval and distinguished it from staff-created invitations. Approved applicants must link to the correct membership, and an invited user should not need a duplicate signup flow. Current delivery and access behavior need checking.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Verify approval and invited-user journeys, company membership and access boundaries with test accounts.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "portal-price-visibility",
    "area": "Orders & pricing",
    "status": "check",
    "title": "Public and signed-in order pricing",
    "description": "Keep public submission prices hidden and show the configured estimate during signed-in ordering.",
    "detail": "The August 20 meeting recorded public pricing hidden and authenticated portal pricing visible, with the quote retained on the submitted order. Later price changes must not rewrite earlier quotes. This historical request has not been matched to the current configuration and release here.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check current public/portal price visibility, order estimates and retained quotes before claiming completion.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "rush-surcharge",
    "area": "Orders & pricing",
    "status": "check",
    "title": "Check the agreed 25% rush surcharge",
    "description": "Check that the rush option uses the recorded surcharge and shows the added amount clearly.",
    "detail": "The August 20 meeting recorded replacing doubled pricing with a 25% surcharge. Whether Rush promises a guaranteed turnaround or needs lab acceptance remained a separate decision. This entry records the request; it does not change prices or establish the current live setting.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the configured surcharge and retained quote; settle the service promise before showing a guaranteed turnaround.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "panel-presets",
    "area": "Receiving",
    "status": "check",
    "title": "Standard and Extended test-panel choices",
    "description": "Offer the configured test packages clearly while preserving individual test selection.",
    "detail": "The August 20 meeting requested Standard and Extended presets, visible included tests and applying a package to selected samples. Reopening saved test selections is a separate released fix. The complete preset behavior still needs a current evidence check.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the lab’s configured package definitions, included tests, bulk application and individual exceptions.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "live-vial-count",
    "area": "Receiving",
    "status": "check",
    "title": "Show vial requirements while choosing tests",
    "description": "Update required vial counts as customers select tests, panels and additional services.",
    "detail": "The August 20 meeting requested immediate vial-count feedback before the final review, plus the same calculation in the order summary. Water volume guidance and Conformity components do not establish all dynamic vial requirements.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check live counts and extra-service requirements across the supported test selections and final review.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "unresolved-client-orders",
    "area": "Orders & operations",
    "status": "check",
    "title": "Find orders still needing a client match",
    "description": "Provide a clear queue or filter for orders that need the existing Resolve Client workflow.",
    "detail": "The August 20 deliverable retained the Resolve Client workflow and recorded better unresolved-order visibility as backlog work. This is separate from fixing a particular missing order. Current queue/filter availability has not been checked.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check existing unresolved-client views and preserve the current resolution process; keep any remaining work in backlog.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "digital-coa-verification",
    "area": "Reports & analyses",
    "status": "check",
    "title": "Visible verification on the digital COA",
    "description": "Make certificate verification obvious at the top and while scrolling.",
    "detail": "The August 20 meeting requested a prominent verified-certificate block and a compact indicator that remains visible while reviewing the digital COA. Invalid, revoked or unavailable records must not appear verified. The public Verify Results lookup and its font mockup are separate surfaces.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the digital COA’s real verification state, scrolling behavior and desktop/phone readability.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "net-content-per-vial",
    "area": "Reports & analyses",
    "status": "check",
    "title": "Report Net Content per vial",
    "description": "Check that peptide Net Content has the agreed per-vial meaning and wording.",
    "detail": "The August 20 deliverable requested per-vial Net Content reporting and consistent Net Content terminology across ordering, result views, reports and imports. Released IU/unit support does not establish the reporting basis or every label. No result conversion is authorized by this entry.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the recorded units, per-vial basis and wording through the complete supported reporting journey.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "coa-status-language",
    "area": "Reports & analyses",
    "status": "check",
    "title": "Consistent test specifications and status wording",
    "description": "Keep Tested, Pass, Within Limits and Identity outcomes distinct where applicable.",
    "detail": "The August 20 deliverable described the Purity minimum specification and green Tested treatment, distinct Identity outcomes and limits-based wording, consistently across PDF and digital COAs. Some related corrections have release records, but the whole requested wording contract has not been checked here. The September 30 meeting again retained Tested versus Pass and visible failures.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Match each requested wording rule to current PDF/digital output and release evidence; preserve the lab’s approved criteria.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "intercompany-supplies",
    "area": "Inventory & operations",
    "status": "check",
    "title": "Partner supplies, running balances and month-end invoices",
    "description": "Track supplies bought for a partner company and keep a reviewable running obligation.",
    "detail": "The August 27 meeting requested vendor/package/paid-price history, mid-month visibility, a complete month-end intercompany invoice and review of older purchases. Existing purchasing history does not prove intercompany settlement or historical backfill. Company roles, accounting rules and approval boundaries need a settled contract before execution.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Review the partner supply and invoicing contract, then check what current software actually supports.",
    "stage": 0,
    "meetingDate": "2026-08-27",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "partner-sample-routing",
    "area": "Inventory & operations",
    "status": "check",
    "title": "Send samples to a partner lab and receive the results",
    "description": "Track partner assignment, custody handoff, returned results and related settlement.",
    "detail": "The August 27 meeting requested associated-lab sharing so work such as metals or solvents could be routed to a partner. Selective permissions are required; an association must not expose every lab or partner. Sharing stock information is a separate request and does not establish sample referral or result return.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Define the permitted partner workflow and check assignment, custody, result return and settlement support.",
    "stage": 0,
    "meetingDate": "2026-08-27",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "intake-attention-notices",
    "area": "Receiving",
    "status": "check",
    "title": "Customer follow-up for intake problems",
    "description": "Let staff record an attention reason and follow up on the affected sample.",
    "detail": "The August 27 meeting requested comments or predefined attention reasons to reduce routine phone calls. This broader follow-up is separate from a received email, the two-stage receipt process, missing white-label vials and customer photo identification. Message scope, wording and complete availability remain unconfirmed.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the general attention-reason workflow and approve the intended notice behavior before enabling customer messages.",
    "stage": 0,
    "meetingDate": "2026-08-27",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "public-coa-boundaries",
    "area": "Reports & analyses",
    "status": "check",
    "title": "Public authenticity details and private full COAs",
    "description": "Keep the public verification record and the full certificate’s sharing rules clear.",
    "detail": "The September 16 and later conversations retained a distinct public authenticity experience, full-COA sharing boundaries and controlled correction of issued artifacts. A working lookup does not settle every public field or white-label editing rule. The September 30 decision keeps existing PDF QR links opening the digital COA.",
    "evidence": "Meeting request recorded; current implementation and release need checking.",
    "nextStep": "Check the public/private field contract and permitted white-label changes; preserve the agreed QR destination.",
    "stage": 0,
    "meetingDate": "2026-09-16",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "shared-lims-priorities",
    "area": "Planning & communication",
    "status": "built",
    "title": "Saved shared priorities inside the LIMS",
    "description": "Let authorized lab users save priorities in the signed-in request list.",
    "detail": "A native LIMS tracker has been built and browser-tested with test accounts, including priority changes, audit records and reload persistence. It is not established as available at Optiq, and its earlier catalog needs reconciliation with this expanded list. The published read-only page does not deliver saved collaboration.",
    "evidence": "Built and tested native candidate; Optiq release and full availability remain unconfirmed.",
    "nextStep": "Reconcile the catalog, complete release checks and confirm the signed-in workflow at Optiq.",
    "stage": 2,
    "meetingDate": "2026-10-02",
    "addedDate": "2026-10-04",
    "meetingPriority": true
  },
  {
    "id": "hubspot-onboarding",
    "area": "Client portal",
    "status": "deferred",
    "title": "HubSpot-to-client onboarding",
    "description": "Avoid entering the same onboarding information in HubSpot and the LIMS.",
    "detail": "The August 20 meeting explicitly deferred this behind urgent sample and COA work. The proposed flow creates a reviewable client draft and keeps staff in control of company matching, recipients and access. No completed integration is claimed.",
    "evidence": "Discussed as later work; no current delivery claimed.",
    "nextStep": "Keep deferred; check existing integration work before prioritizing a reviewed onboarding flow.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04"
  },
  {
    "id": "client-specific-pricing",
    "area": "Orders & pricing",
    "status": "deferred",
    "title": "Client-specific prices and discounts",
    "description": "Support configured customer prices without exposing another customer’s pricing.",
    "detail": "The August 20 meeting described this as future architecture rather than immediate launch scope. List prices, discounts and the submitted quote need separate retained values. It should not delay more urgent sample and COA work.",
    "evidence": "Discussed as later work; no current delivery claimed.",
    "nextStep": "Keep deferred and check existing pricing capabilities before scheduling remaining work.",
    "stage": 0,
    "meetingDate": "2026-08-20",
    "addedDate": "2026-10-04"
  },
  {
    "id": "customer-qr-labels",
    "area": "Reports & analyses",
    "status": "proposed",
    "title": "Explore customer vial QR labels",
    "description": "Consider printable vial labels linked to the certificate or verification experience.",
    "detail": "The September 30 meeting explored customer vial labels and a possible external printing service. This is different from the existing internal printed-label choices. No provider, spending decision or committed delivery was established.",
    "evidence": "Exploratory idea recorded; scope and approval remain separate.",
    "nextStep": "Decide whether to pursue customer labels; retain this as an idea until the scope is agreed.",
    "stage": 0,
    "meetingDate": "2026-09-30",
    "addedDate": "2026-10-04"
  },
  {
    "id": "watched-folder-documents",
    "area": "Inventory & operations",
    "status": "proposed",
    "title": "Explore a watched folder for business documents",
    "description": "Consider dropping invoices, packing slips and photographed documents into a local collection folder.",
    "detail": "The August 27 meeting explored extending low-friction collection beyond instrument files. The wider business-document scope and speaker commitment were uncertain. Existing Empower source collection does not establish this separate workflow.",
    "evidence": "Exploratory idea recorded; scope and approval remain separate.",
    "nextStep": "Keep as an idea; define the document scope and approved handling before any build or activation.",
    "stage": 0,
    "meetingDate": "2026-08-27",
    "addedDate": "2026-10-04"
  },
  {
    "id": "coa-tamper-evidence",
    "area": "Reports & analyses",
    "status": "proposed",
    "title": "Evaluate tamper evidence for issued COAs",
    "description": "Explore a defensible link between an issued certificate and its retained source evidence.",
    "detail": "The August 27 and September 30 discussions raised tamper evidence and possible blockchain anchoring. Those conversations do not settle a technology, public claim, timing or activation policy. Legitimate lab corrections and controlled reissue must remain possible.",
    "evidence": "Exploratory idea recorded; scope and approval remain separate.",
    "nextStep": "Evaluate the required evidence and lifecycle contract first; do not treat a technology idea as an approved build.",
    "stage": 0,
    "meetingDate": "2026-08-27",
    "addedDate": "2026-10-04"
  }
];
