window.OPTIQ_REQUESTS = [
  {
    "id": "conformity",
    "area": "Reports & analyses",
    "status": "optiq",
    "title": "Conformity testing",
    "description": "Compare several vials for Net Content, Purity, or Identity, with repeat results and a summary on the COA.",
    "detail": "The repeat-vial workflow and a detailed COA layout have been built in parts. The September 30 meeting agreed to use full test names, allow a suitable original result to count as the first repeat, and put the detailed results on an extra page. The lab still needs to confirm the standard, acceptable variation, which tests the customer can order, and pricing before the final setup can be finished.",
    "question": "Confirm the standard and acceptable variation for each test, which tests customers can order, and the repeat-vial price.",
    "evidence": "Work started; lab pricing and pass/fail rules still needed.",
    "stage": 1,
    "nextStep": "Confirm the test rules, ordering choices, and repeat-vial price.",
    "discussedDate": "2026-10-02",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "inspection-rules",
    "area": "Receiving",
    "status": "optiq",
    "title": "Visual inspection and COA rules",
    "description": "Agree what the visual check records and which findings should appear on the COA.",
    "detail": "The lab will review examples from other testing labs. Seal integrity, cap color, and an intact vial are the starting checks. Recording powder appearance or visible amount, and handling damaged or empty vials on the COA or through customer follow-up, still need the lab’s decision.",
    "question": "Share inspection examples and confirm what to record, including powder appearance or visible amount, and which problems belong on the COA or need a customer reply first.",
    "evidence": "Starting checks agreed; final inspection and COA rules still needed.",
    "stage": 0,
    "nextStep": "Share inspection examples and confirm what to record, including powder appearance or visible amount, and which problems belong on the COA or need a customer reply first.",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "batch-templates",
    "ref": "R31",
    "area": "Inventory & operations",
    "status": "optiq",
    "title": "Batch and preparation sheets",
    "description": "Use repeatable daily preparation sheets and put vials in the correct instrument order.",
    "detail": "Some of the tools are already available. We need the lab’s worksheet and vial order to tailor them to Optiq.",
    "question": "Share your current preparation sheet and the order vials should run in.",
    "evidence": "Starting tools available; lab details needed.",
    "stage": 0,
    "nextStep": "Share your current preparation sheet and the order vials should run in."
  },
  {
    "id": "verify-results",
    "status": "complete",
    "stage": 3,
    "title": "Verify Results — real certificate lookup",
    "description": "Look up a certificate on the Optiq website and compare it with the lab’s released record.",
    "detail": "The website was connected to real released COAs and tested with an older printed certificate number, the sample photo, and a phone-sized screen. The recorded release was September 27. The September 30 font adjustment is listed separately. The meeting agreed to keep the COA’s QR code opening its digital version.",
    "evidence": "Released and checked on the Optiq website · 27 Sep 2026.",
    "nextStep": "Available on the website; keep the QR code opening the digital COA.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "verify-results-font",
    "status": "queued",
    "stage": 0,
    "title": "Verify Results — match the website font",
    "description": "Make the verification page’s text feel consistent with the Optiq website.",
    "detail": "The September 30 meeting requested a font adjustment and an example of the updated page. The real lookup is already released. There is no matching record confirming that this later font adjustment has been released.",
    "evidence": "Font adjustment requested · 30 Sep 2026.",
    "nextStep": "Finish the agreed font adjustment and show the updated page.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "coa-mass-spectra",
    "status": "built",
    "stage": 2,
    "title": "Mass spectra on COAs",
    "description": "Choose one or more measured spectra and show them with the sample’s chromatogram, including blends.",
    "detail": "The spectrum picker, saved selections, and separate labeled COA pages are built and tested. The default for choosing peaks was changed to PDA in the recorded 1 October release and is listed separately. Complete instrument imports and final COA generation at Optiq still need matching proof. Multiple spectra can be selected for a blend; that alone does not establish complete delivery.",
    "evidence": "Spectrum selection and multi-spectrum COA pages built and tested.",
    "nextStep": "Confirm the full import → selected spectra → generated COA journey at Optiq.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "spectral-reference-library",
    "status": "built",
    "stage": 2,
    "title": "Reference standards for spectrum comparisons",
    "description": "Keep the lab’s reference spectra in a library and compare samples against them.",
    "detail": "The September 30 meeting requested a standards selector and a reusable library. A lab-owned library with draft standards, source records, and saved comparisons has since been built and tested. It is not released at Optiq. These comparisons do not automatically confirm Identity or change a released COA; the lab must establish the standards and method used.",
    "evidence": "Library and comparison screens built and tested; not released.",
    "nextStep": "Finish the current build checks and merge steps, then release and validate the library with the lab’s chosen standards.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "fentanyl-results",
    "status": "queued",
    "stage": 0,
    "title": "Fentanyl test results",
    "description": "Record the fentanyl test outcome and show it clearly on the COA.",
    "detail": "The September 30 meeting requested a simple outcome such as detected or not detected, with an agreed pass/fail presentation. That display request is recorded. A matching completed feature or release record was not found. Final wording must follow the lab’s actual test and reporting rules.",
    "evidence": "Requested · 30 Sep 2026; implementation planned.",
    "nextStep": "Add the result entry and COA display, then check them against the lab’s reporting rules.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "requested-white-label-photo",
    "status": "queued",
    "stage": 0,
    "title": "Choose the photo on a customer’s white-label request",
    "description": "Let authorized lab staff change the selected photo while reviewing a customer-requested white-label COA.",
    "detail": "On September 30 the lab reported that the photo could not be changed when the customer had requested the COA. The existing private-draft editor does not cover requests still awaiting customer-request approval. This specific case needs a fix and a screen test. Changes must keep the previously released certificate intact.",
    "evidence": "Specific photo-selection problem recorded · 30 Sep 2026.",
    "nextStep": "Fix photo selection during lab review and test it before approval.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "coa-summary-layout",
    "status": "queued",
    "stage": 0,
    "title": "COA summary with extra test pages",
    "description": "Keep the first page easy to read, with detailed Conformity results and spectra on following pages.",
    "detail": "The September 30 meeting agreed on a useful first-page snapshot, followed by the detailed results. The COA can already span pages, and the Conformity layout is built. Bringing together the extra tests, visual checks, and spectra still needs work. Use full test names and preserve the distinction between Tested, Pass, and a failed result.",
    "evidence": "Page structure agreed · 30 Sep 2026; existing layouts available.",
    "nextStep": "Finish and check the first-page summary and extra pages with the new tests.",
    "area": "Reports & analyses",
    "meetingDate": "2026-09-30"
  },
  {
    "id": "receipt-emails",
    "area": "Receiving",
    "status": "built",
    "title": "Sample-received emails",
    "description": "Tell customers when all or some of their samples have arrived.",
    "detail": "Receipt emails are built and tested with a test inbox. The 2 October call made release a priority, but did not establish that customers received them. The approved photo-and-answer flow is a separate item. A complete two-stage drop-off and verification message sequence is not established by these email tests.",
    "evidence": "Built and tested; checking availability and delivery.",
    "stage": 2,
    "nextStep": "Confirm the release and delivery of receipt emails to the correct customers at Optiq.",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "customer-photos",
    "area": "Receiving",
    "status": "built",
    "title": "Customer photo requests and replies",
    "description": "Send a customer a photo when the lab cannot identify a sample, then review their answer.",
    "detail": "The approved photo-and-answer flow is built and has passed real browser tests with test accounts. Staff choose the customer, order, and photo; the customer picks the matching sample or “None of these samples.” Staff review the reply before closing the request. Final checks and release are still pending.",
    "evidence": "Built and browser-tested · 2 Oct 2026; not released.",
    "stage": 2,
    "nextStep": "Finish the remaining checks and release the approved flow to Optiq.",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "inspection-checks",
    "area": "Receiving",
    "status": "queued",
    "title": "Seal integrity, cap color, and intact vials",
    "description": "Record three checks when samples arrive: whether the seal is intact, the cap color, and whether the vial is intact or broken.",
    "detail": "Today’s call agreed these three checks as the starting point. Some receiving checks exist already, but seal observations still need to save correctly. All three checks then need testing.",
    "evidence": "Three starting checks agreed · 2 Oct 2026; remaining work planned.",
    "stage": 0,
    "nextStep": "Add the three agreed checks, make sure they save, and test them.",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "invoice-status",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Invoice status",
    "description": "See and update invoice status in Reporting Hub.",
    "detail": "The Invoiced, Paid, and Unpaid dropdown, saving, paste/fill, and undo/redo are built and have recorded screen-test proof. Earlier feedback said this was fixed. The current Optiq screen and matching delivery evidence have not been independently confirmed by this audit.",
    "evidence": "Built; use at Optiq still needs confirmation.",
    "stage": 2,
    "nextStep": "Confirm the requested dropdown and editing behavior on the current Optiq screen."
  },
  {
    "id": "frozen-sort",
    "area": "Reports & analyses",
    "status": "queued",
    "title": "Keep rows still while editing",
    "description": "Keep a row in place while you edit it, then sort again when you are ready.",
    "detail": "Reporting Hub already sorts rows. The option to hold that order while editing still needs to be added and tested.",
    "evidence": "Planned.",
    "stage": 0,
    "nextStep": "Add the option to keep rows still and sort again when finished."
  },
  {
    "id": "lot-number",
    "area": "Receiving",
    "status": "built",
    "title": "Lot / Batch number",
    "description": "Show the Lot / Batch number automatically in the sample receiving table.",
    "detail": "The change is built and has been checked on screen. We still need to confirm it is available at Optiq. Saved layouts may need “Reset to Lab Default.”",
    "evidence": "Built and tested; checking availability at Optiq.",
    "stage": 2,
    "nextStep": "Confirm the Lot / Batch column appears at Optiq."
  },
  {
    "id": "printed-labels",
    "area": "Labels",
    "status": "queued",
    "title": "Printed label choices",
    "description": "Choose separately whether labels show test symbols, three-letter test names, or both.",
    "detail": "Labels can already be printed. These separate choices still need to be added, then checked on actual printed labels.",
    "evidence": "Planned.",
    "stage": 0,
    "nextStep": "Add the choices and check the printed labels."
  },
  {
    "id": "client-scrolling",
    "area": "Client management",
    "status": "complete",
    "title": "Manage Clients scrolling",
    "description": "Scroll through the client list without the reported problem.",
    "detail": "Earlier feedback confirmed the problem was fixed. If it happens again, we will need an example to investigate.",
    "evidence": "Reported fixed.",
    "stage": 3,
    "completed": "Reported resolved",
    "nextStep": "No further work recorded."
  },
  {
    "id": "net-content-editing",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Net Content copy, paste, and fill",
    "description": "Enter Net Content amounts and units, or copy them across several rows.",
    "detail": "Value-only and value-with-unit copy, paste, and fill are built and have recorded save-and-reload screen tests. This is separate from adding IU and changing the lab’s allowed units. Current availability at Optiq still needs confirmation; reliable undo of a drag-fill is a separate follow-up.",
    "evidence": "Built and tested; current Optiq use not confirmed.",
    "stage": 2,
    "nextStep": "Confirm copy, paste, and drag-fill on the current Optiq screen."
  },
  {
    "id": "universal-import",
    "area": "Reports & analyses",
    "status": "partial",
    "title": "Import results by Sample ID",
    "description": "Upload result files and match each result to the correct Sample ID.",
    "detail": "Importing exists for chemistry panels and Net Content. We are checking whether it covers every peptide test in the request.",
    "evidence": "Partly built; the remaining peptide tests still need to be checked.",
    "stage": 2,
    "nextStep": "Check that every requested peptide test can use the import."
  },
  {
    "id": "grid-widths",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Readable columns and width choices",
    "description": "Let columns widen to fit their contents, or keep a width you choose.",
    "detail": "Both options are built. We have not yet confirmed they have been made available at Optiq.",
    "evidence": "Built; waiting to be made available.",
    "stage": 2,
    "nextStep": "Make the column improvements available at Optiq and check them."
  },
  {
    "id": "inventory-release",
    "area": "Inventory & operations",
    "status": "complete",
    "title": "Inventory and reference-standard values",
    "description": "Manage inventory, test substances, certified lot values, and receiving in the updated Inventory screens.",
    "detail": "Our release records show the agreed Inventory update was made available on 28 September 2026.",
    "evidence": "Released · 28 Sep 2026.",
    "stage": 3,
    "completed": "Recorded release",
    "nextStep": "Released · 28 Sep 2026."
  },
  {
    "id": "iu-units",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "IU and Net Content units",
    "description": "Report Net Content in IU or other units selected by the lab.",
    "detail": "Our release records show this was made available on 1 October 2026. Existing saved amounts and units were kept without converting the numbers.",
    "evidence": "Released · 1 Oct 2026.",
    "stage": 3,
    "completed": "Recorded release",
    "nextStep": "Released · 1 Oct 2026."
  },
  {
    "id": "preview-performance",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Faster photo and chart previews",
    "description": "Load smaller previews of photos, chromatograms, and spectra in Reporting Hub.",
    "detail": "The improvement was released on 1 October 2026. Scrolling was tested before release; its speed during everyday use at Optiq has not been measured separately.",
    "evidence": "Released · 1 Oct 2026.",
    "stage": 3,
    "completed": "Recorded release",
    "nextStep": "Released · 1 Oct 2026."
  },
  {
    "id": "sop-documents",
    "area": "Inventory & operations",
    "status": "built",
    "title": "Documents, Forms, Logs, and NCRs",
    "description": "Edit documents, keep earlier versions, correct forms and logs, and track quality issues such as nonconformance reports (NCRs).",
    "detail": "These features have been built and tested on screen. Making them available at Optiq is still pending. Document signing and shared templates are listed separately.",
    "evidence": "Built and tested; waiting to be made available.",
    "stage": 2,
    "nextStep": "Finish the release checks and make these features available at Optiq."
  },
  {
    "id": "partner-inventory",
    "area": "Inventory & operations",
    "status": "working",
    "title": "Sharing stock information with partner labs",
    "description": "Choose which stock information a partner lab can see while keeping each lab’s inventory separate.",
    "detail": "Work has started on choosing what to share. Requests, transfers, receiving, and handling missing or damaged items are not yet complete.",
    "evidence": "Partly built; partner-lab process still needs work.",
    "stage": 1,
    "nextStep": "Finish how partner labs request, transfer, and receive stock."
  },
  {
    "id": "manufacturer-profiles",
    "area": "Reports & analyses",
    "status": "queued",
    "title": "Saved manufacturers and early white-label requests",
    "description": "Choose a saved manufacturer and request a white-label COA when submitting samples.",
    "detail": "Manufacturer names can already be entered by hand. Choosing a saved manufacturer and recording the white-label request during submission still need work.",
    "evidence": "Planned; manual name entry already available.",
    "stage": 0,
    "nextStep": "Add saved manufacturer choices and white-label requests during submission."
  },
  {
    "id": "client-bulk-white-label",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Client requests for several white-label COAs",
    "description": "Let clients request white-label COAs for several samples at once.",
    "detail": "The client bulk-request screen and the steps for saving and submitting several white-label COAs are built. Screen tests and software checks are recorded. We have not confirmed current availability for Optiq’s client accounts.",
    "evidence": "Built and tested; client availability at Optiq still needs confirmation.",
    "stage": 2,
    "nextStep": "Confirm that Optiq clients can open and use the bulk-request screen."
  },
  {
    "id": "white-label-drafts",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Private white-label drafts",
    "description": "Edit a draft COA and the client name printed on it before it is released.",
    "detail": "The changes are built and have passed software checks. The screens still need to be tested, and availability at Optiq has not been confirmed. This covers eligible private drafts; changing the photo on a customer request still awaiting approval is a separate item below.",
    "evidence": "Built; screen checks and release still needed.",
    "stage": 2,
    "nextStep": "Complete the real screen test, finish the review and merge steps, and confirm release to Optiq."
  },
  {
    "id": "blend-potency",
    "area": "Reports & analyses",
    "status": "queued",
    "title": "Results for each peptide in a blend",
    "description": "Enter a separate result for each peptide in a blend and show those results on the COA.",
    "detail": "The COA layout is ready. Entering each peptide’s result and carrying it through to the report still need work.",
    "evidence": "COA layout ready; result entry planned.",
    "stage": 1,
    "nextStep": "Add separate peptide results and check they appear correctly on the COA."
  },
  {
    "id": "photo-reliability",
    "area": "Receiving",
    "status": "complete",
    "title": "Clear intake photos and hide / restore orders",
    "description": "View clear original photos and hide or restore an order in Intake without deleting its samples or results.",
    "detail": "These features were released to Optiq on 9 September 2026. Full-size photos and hiding, reloading, and restoring an order were tested before release. The separately reported missing order is listed as its own item.",
    "evidence": "Released · 9 Sep 2026.",
    "stage": 3,
    "nextStep": "Released · 9 Sep 2026.",
    "completed": "Recorded release"
  },
  {
    "id": "scan-intake",
    "area": "Receiving",
    "status": "working",
    "title": "Scan, review, and receive samples",
    "description": "Scan an order, review and correct its sample list, then confirm what arrived.",
    "detail": "The requested intake-station scan must open an order for manual review, with staff able to add, remove, rename, or confirm samples before recording receipt. Scanning must not automatically receive samples. Separate physical drop-off and verified-intake steps were also requested; the existing receipt email does not prove that complete two-stage flow. Staff search and order-form scanning are built and listed separately.",
    "evidence": "Partly built; complete receiving process still needs work.",
    "stage": 1,
    "nextStep": "Finish and test stationary scanning, manual sample review, and separate drop-off and verified-intake steps."
  },
  {
    "id": "certified-imports",
    "area": "Inventory & operations",
    "status": "queued",
    "title": "Export and import certified lot values",
    "description": "Export lot values as a CSV spreadsheet file and read values from a reference-standard COA.",
    "detail": "Values can already be entered by hand. Spreadsheet export and reading values from a document are still planned.",
    "evidence": "Manual entry available; import and export planned.",
    "stage": 0,
    "nextStep": "Add spreadsheet export and importing values from a COA."
  },
  {
    "id": "purchasing",
    "area": "Inventory & operations",
    "status": "working",
    "title": "Purchasing follow-ups",
    "description": "Handle vendor replies, suggest values from invoices, manage item requests, and flag orders needing attention.",
    "detail": "Order history, imports, and tracking are built and listed separately. These additional purchasing features still need to be finished and made available.",
    "evidence": "Further purchasing features in progress.",
    "stage": 1,
    "nextStep": "Finish vendor replies, invoice suggestions, and the expanded attention list."
  },
  {
    "id": "instrument-workflow",
    "ref": "R02",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Empower run lists and source files",
    "description": "Prepare instrument run lists and keep track of the original data and where it came from.",
    "detail": "Run-list and source-file provenance tools have been built. Their use on the lab’s instrument computer is not yet confirmed. Automatic native Empower collection and the released native-chart display repair are separate items in this list.",
    "evidence": "Built; instrument setup and use not yet confirmed.",
    "stage": 2,
    "nextStep": "Confirm the run-list and source-file workflow works with the lab’s instrument computer."
  },
  {
    "id": "retained-intent",
    "ref": "R03",
    "area": "Receiving",
    "status": "queued",
    "title": "Recover archived portal request details",
    "description": "Keep the original details of older portal requests so they can be found and recovered.",
    "detail": "This request is on the planned list. A matching finished feature has not been verified. The next step is to match the original request to the existing archive tools, then finish and test any missing recovery steps.",
    "evidence": "Planned; no matching completed feature verified.",
    "stage": 0,
    "nextStep": "Match the original request to the archive tools, then finish and test the missing steps."
  },
  {
    "id": "intake-identity",
    "ref": "R33",
    "area": "Receiving",
    "status": "complete",
    "title": "Peptide names and mixtures during intake",
    "description": "Clearly show which peptide or mixture is being submitted in the intake table.",
    "detail": "Peptide names and mixtures can be selected directly in the sample table. Saved choices are retained when the page is reloaded, and the Peptide Identity column follows Sample Type. These changes were released to Optiq on 10 September 2026.",
    "evidence": "Released · 10 Sep 2026.",
    "stage": 3,
    "nextStep": "Released · 10 Sep 2026.",
    "completed": "Recorded release"
  },
  {
    "id": "analysis-framework",
    "area": "Reports & analyses",
    "status": "working",
    "title": "Lab-specific testing steps",
    "description": "Set up the lab’s preparation, result entry, and review steps for each test.",
    "detail": "The first method-setup tools are built and listed separately. The full process still needs to carry the correct results from entry through review to the COA.",
    "evidence": "Setup tools partly ready; complete testing process still needs work.",
    "stage": 1,
    "nextStep": "Finish and test the steps from preparation and result entry through to the COA."
  },
  {
    "id": "document-release",
    "area": "Inventory & operations",
    "status": "queued",
    "title": "Document signing and shared templates",
    "description": "Approve and sign the current document version, and reuse templates across labs.",
    "detail": "Document editing and saved versions are built. The complete signing and release process, and sharing templates across labs, still need work.",
    "evidence": "Planned follow-up to the document editor.",
    "stage": 0,
    "nextStep": "Finish document approval, signing, and shared templates."
  },
  {
    "id": "purchasing-core",
    "area": "Inventory & operations",
    "status": "built",
    "title": "Purchasing history, imports, and tracking",
    "description": "Track each purchase order, import earlier orders, and see which orders need attention.",
    "detail": "These features are built and have been checked. We still need to confirm that everything required is installed and available at Optiq.",
    "evidence": "Built and checked; availability at Optiq not confirmed.",
    "stage": 2,
    "nextStep": "Check that the purchasing features are installed and available at Optiq."
  },
  {
    "id": "reporting-method-drafts",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Draft method setup",
    "description": "Use existing report fields to prepare a draft method in Analysis Settings.",
    "detail": "Creating and saving inactive method drafts was built and tested, then included in the recorded Optiq release on 1 October 2026. A saved draft does not activate a test method or complete its result-entry and COA workflow. The signed-in live draft screen has not been separately verified.",
    "evidence": "Recorded release · 1 Oct 2026; signed-in live use not confirmed.",
    "stage": 3,
    "nextStep": "Confirm signed-in use at Optiq; full testing workflows remain a separate item.",
    "completed": "Recorded release"
  },
  {
    "id": "staff-scan-access",
    "area": "Receiving",
    "status": "built",
    "title": "Staff search and order-form scanning",
    "description": "Let signed-in lab staff search and use “Scan label” on the order form.",
    "detail": "This change is built. Saving, photo uploads, and editing locks still need their existing permissions. Scanning on the separate intake screen is not covered by this change. Availability at Optiq is not yet confirmed.",
    "evidence": "Built · 2 Oct 2026; availability not confirmed.",
    "stage": 2,
    "nextStep": "Check that staff can search and scan labels on Optiq’s order form."
  },
  {
    "id": "multi-lab-login",
    "area": "Lab access",
    "status": "queued",
    "title": "One login and easy lab switching",
    "description": "Use one personal login and switch between the labs you are allowed to access.",
    "detail": "Today’s call preferred an easy lab selector, like switching companies in QuickBooks. Each lab keeps its own dashboard, reports, and permissions. A design is ready, but this has not been built or released.",
    "evidence": "Design ready; building is planned.",
    "nextStep": "Build and test personal logins with a lab selector and separate permissions for each lab.",
    "stage": 0,
    "addedDate": "2026-10-02",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "shared-feature-tracker",
    "area": "Planning & communication",
    "status": "complete",
    "title": "Shared feature list and questions",
    "description": "Share one list of requests, progress, and questions for the lab.",
    "detail": "The public tracker is published and checked. Anyone with the link can read the list, search requests, open the details, and copy the lab questions. Lab replies can be collected in the shared discussion and used to update the list.",
    "evidence": "Published and checked · 2 Oct 2026.",
    "nextStep": "Share the link and use the shared discussion for lab answers.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "discussedDate": "2026-10-02"
  },
  {
    "id": "missing-order-recovery",
    "area": "Receiving",
    "status": "complete",
    "title": "Reported missing order",
    "description": "Resolve the report about a photo-heavy order that appeared to be missing.",
    "detail": "The report about the missing order has been cleared up. No further action is needed for this item.",
    "evidence": "Reported resolved · 2 Oct 2026.",
    "nextStep": "Resolved · 2 Oct 2026.",
    "stage": 3,
    "completed": "Reported resolved",
    "resolvedDate": "2026-10-02"
  },
  {
    "id": "net-content-undo",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Undo a Net Content drag-fill",
    "description": "Undo a fill across several samples and keep the restored values after saving.",
    "detail": "The follow-up fix is written and has passed software tests. Its real screen test and independent review are still pending. It has not been released; the existing copy, paste, and fill feature is listed separately.",
    "evidence": "Fix built; screen test and review pending.",
    "nextStep": "Test undo and reload on the real screen, complete review, and confirm release.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "bulk-coa-amendments",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Correct several COAs together",
    "description": "Prepare corrected COAs for several selected samples while preserving the earlier released certificates.",
    "detail": "The bulk amendment fix is built and has recorded software checks. It checks which samples can be amended and preserves the prior released COA until a replacement is released. Current availability at Optiq and a complete amendment journey have not been confirmed here. This is separate from bulk white-label requests.",
    "evidence": "Built; current Optiq availability and full journey not confirmed.",
    "nextStep": "Confirm the complete select → generate → review → replacement-release journey at Optiq.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "pda-peak-default",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Use PDA first when choosing spectrum peaks",
    "description": "Start peak selection from the PDA chromatogram while using the mass-spectrum data for the spectrum.",
    "detail": "The PDA default was built and tested, then included in the recorded Optiq release on 1 October 2026. Staff can still explicitly choose the other supported peak source, and the existing fallback remains when PDA is unavailable. The signed-in live picker has not been separately verified.",
    "evidence": "Recorded release · 1 Oct 2026; signed-in live picker not confirmed.",
    "nextStep": "Confirm the PDA default in the signed-in Optiq picker.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "completed": "Recorded release"
  },
  {
    "id": "native-empower-charts",
    "area": "Reports & analyses",
    "status": "complete",
    "title": "Display charts from native Empower source data",
    "description": "Show charts when retained native Empower evidence is available.",
    "detail": "The chart display repair was included in the recorded Optiq release on 1 October 2026. Stored-trace rendering was tested locally, and release and health checks were recorded. This repairs how available evidence is displayed; it does not prove every run has been imported or that automatic collection is active.",
    "evidence": "Recorded release · 1 Oct 2026; complete collection remains separate.",
    "nextStep": "Confirm the affected sample charts during normal lab use.",
    "stage": 3,
    "addedDate": "2026-10-02",
    "completed": "Recorded release"
  },
  {
    "id": "empower-native-collection",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Automatic Empower imports and recovery",
    "description": "Collect completed Empower runs without a manual export and recover interrupted imports.",
    "detail": "The source collector, retained data, sample matching, recovery tools, and local status screen are built with recorded tests. Installation, secure setup, and activation at Optiq remain separate release steps. A normal subsequent lab run, live interruption recovery, and import timing still need acceptance proof. No complete instrument delivery is claimed.",
    "evidence": "Built and tested; installation, activation, and live acceptance pending.",
    "nextStep": "Prepare and release the collector, then verify a normal run and interrupted-import recovery.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "inventory-follow-ups",
    "area": "Inventory & operations",
    "status": "partial",
    "title": "Remaining Inventory screens and AI tools",
    "description": "Finish the remaining Inventory redesign and assisted entry tools.",
    "detail": "The earlier Inventory bundle is released. New Vendors, Equipment, and Composites screens have since been built, while the wider redesign and AI tools remain incomplete. Purchasing, certified-value import, and reorder suggestions have their own rows so completed pieces are not hidden inside this larger request.",
    "evidence": "Some later screens built; full redesign and AI scope incomplete.",
    "nextStep": "Finish the remaining screens and AI tools, validate each piece, and confirm release.",
    "stage": 1,
    "addedDate": "2026-10-02"
  },
  {
    "id": "purchasing-status-words",
    "area": "Inventory & operations",
    "status": "built",
    "title": "Use the lab’s own purchasing status words",
    "description": "Show familiar status words on purchase-order lines and retain them in history.",
    "detail": "Lab-specific words and their saved history are built and tested on a private screen. They describe the existing purchasing steps; they do not replace the underlying order status. Current availability at Optiq is not confirmed.",
    "evidence": "Built and screen-tested; current Optiq availability not confirmed.",
    "nextStep": "Confirm the status-word settings and saved history are available at Optiq.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "purchase-history-forecast",
    "area": "Inventory & operations",
    "status": "built",
    "title": "Reorder suggestions from purchase history",
    "description": "See when regularly purchased items are usually due for another order.",
    "detail": "The history-based suggestions are built and tested on a private screen. They show typical ordering patterns, rather than claiming that stock is low. They do not automatically place an order. Current availability at Optiq is not confirmed.",
    "evidence": "Built and screen-tested; current Optiq availability not confirmed.",
    "nextStep": "Confirm the suggestions are available at Optiq and useful with the lab’s purchase history.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "water-sample-type",
    "area": "Receiving",
    "status": "built",
    "title": "Water sample type and clear sample symbols",
    "description": "Offer Water during submission and show consistent symbols for sample types.",
    "detail": "The Water option has recorded software tests, and the shared sample-type symbols have recorded screen checks. The Water option also requires its reviewed setup before release. These changes remain open build candidates; current Optiq availability is not confirmed. This does not settle the separate non-peptide or B12 identity question.",
    "evidence": "Built candidates; final checks, setup, and release pending.",
    "nextStep": "Finish the candidates’ checks and setup, then confirm the options on the Optiq submission screen.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "saved-order-selections",
    "area": "Receiving",
    "status": "built",
    "title": "Restore the selected tests in saved orders",
    "description": "Reload a saved order with its chosen tests shown on the correct tiles.",
    "detail": "The fix is built and has software checks and recorded review. It reconciles saved choices with the tests the lab actually offers and warns about unavailable selections. Remaining review follow-ups and the current Optiq screen outcome are not confirmed complete.",
    "evidence": "Fix built; remaining follow-ups and Optiq availability not confirmed.",
    "nextStep": "Finish the recorded follow-ups and validate a saved order after reload at Optiq.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "order-submit-retry",
    "area": "Receiving",
    "status": "built",
    "title": "Recognize an order already submitted",
    "description": "After a retry or reload, show the order that was already placed.",
    "detail": "The fix is built and tested in software for the saved-order path. A real screen test with the running system is still needed. It does not cover submissions where no saved order was opened. It remains an open candidate and is not a confirmed Optiq release.",
    "evidence": "Fix built; real screen test and release pending.",
    "nextStep": "Test submission retry and reload, finish review, and confirm release.",
    "stage": 2,
    "addedDate": "2026-10-02"
  },
  {
    "id": "configured-sample-actions",
    "area": "Reports & analyses",
    "status": "built",
    "title": "Lab-configured Sample Details and repeat-work actions",
    "description": "Show the lab’s actual tests and supported repeat-work actions on Sample Details.",
    "detail": "The candidate uses the lab’s configured tests and permissions for result views, re-run, re-prep, confirmation, and cancel. Recorded real browser tests used test samples. Final merge and release are still pending, and unsupported testing workflows remain unavailable. This is a built part of the wider lab-specific testing framework.",
    "evidence": "Built and browser-tested candidate; release pending.",
    "nextStep": "Finish the candidate’s remaining checks and confirm release and use at Optiq.",
    "stage": 2,
    "addedDate": "2026-10-02"
  }
];
